# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_made', models.CharField(max_length=1000)),
                ('quote_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quote_which_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Comment')),
            ],
        ),
    ]
