# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_made',
            field=models.TextField(max_length=1000),
        ),
    ]
