# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170530_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='this_comment_quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Quote'),
        ),
    ]
