# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_this_comment_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_by',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote_which_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='this_comment_quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Comment'),
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
