# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170606_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='color',
            field=models.CharField(blank=True, choices=[('yellow', 'yellow'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('purple', 'purple'), ('black', 'black')], default='black', help_text='Change Text Color', max_length=6),
        ),
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(blank=True, choices=[('yellow', 'yellow'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('purple', 'purple'), ('black', 'black')], default='black', help_text='Change Text Color', max_length=6),
        ),
    ]
