# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170608_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='pin_post',
            field=models.ManyToManyField(blank=True, to='main.Post'),
        ),
    ]
