# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userextend_pin_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
