# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-10 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170609_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_pix',
            field=models.ManyToManyField(blank=True, to='main.Attachment'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_pix',
            field=models.ManyToManyField(blank=True, to='main.Attachment'),
        ),
    ]
