# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_post_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='status',
        ),
        migrations.AddField(
            model_name='userextend',
            name='gender',
            field=models.CharField(blank=True, choices=[(' ', '------'), ('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='brief_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brief Description'),
        ),
    ]
