# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170629_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
