# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-08 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_section_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_move_to_fp', 'Change frontpage status'),)},
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No'), ('t', 'Trash')], default='n', help_text='Move To Frontpage?', max_length=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
