# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-09 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20170708_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
